### ISSUE TITLE
ID 8905 not reported correctly

### ISSUE THREAD

**Issue by jwjsystem** [wpwhitesecurity/activity-log-tablepress#11]
Plugin is not reporting correctly and completely, the changes performed in a table cell - I was expecting to see the **previous** and **new** value changes captured by the plugin (not just NULL).

Instead of ID 8905 (a table was modified), I get only **8908** IDs _(a table option was modified -- which should not be the case)_ , but with "NULL" reported instead of capturing the actual values.

Steps to reproduce:
1. create or import a table with Tablepress
2. edit a cell with a new value
3. save changes

You will notice an ID 8908 reported as in the screenshot below.

![w](https://user-images.githubusercontent.com/92275653/226362135-d1eff587-29e4-46eb-ab36-c5c7940245e0.png)

Expected **result:**

![w](https://user-images.githubusercontent.com/92275653/226363318-4035df29-26b3-423b-92b7-acc640edf325.png)

**Comment by sdobreff** [comment]
Can not reproduce

**Comment by jwjsystem** [comment]
@sdobreff https://www.loom.com/share/2dbc9d1e6ca640d480a5fd1704b2704d 

Not sure if this is the expectancy in terms of ID reported , or if we can do anything to show up more relevant data on what actually cell was modified etc.

**Comment by jwjsystem** [comment]
Discussed that it's almost impossible resourcewise to check the table contents which was modified since it's way too big.

Closing since not an actual issue.
